### ISSUE TITLE
ecmo 코로나 환자 여부에 따른 처방 건수 요청. - 윤다슬 선생님

### ISSUE THREAD

**Issue by GritYourMind** [kyoungman00/cbnuh_todo#21]
## 요청내용 2023-04-10 
- 20200703 ~ 20230331
- U099,  U071, U072, U089, U109, U119, B342, B972 (이승희팀장님 확인) 진단(코로나) 여부 에 따른 
- MIF_CD IN ('H3394','H3395','H3382') 처방 건수 요청.

**Comment by kyoungman00** [comment]
## 2023-04-11
- 회신 완료.
